[theme]
primaryColor = "#111827"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
port = 8501

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
